
spring:
  application:
    name: micro-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
server:
  port: 8280